open Ast
open Float
open List
open Printf
open Sys
open Unix

(** [Translater] module generates SMT formulas from an LLL file.
	The approach used consists of converting each boolean stream
	into a function taking a timestep as a parameter and
	outputting true or false. The module produces an SMT file by
	PO and by depth, then runs the Z3 solver by increasing depth
	on each PO. It is advisable to use [generate_smt_bv] because
	the performance of the BitVec type in SMT is much better than
	that of the Int type generated by [generate_smt_int].*)

(** [bits_from_int i] calculates the number of bits needed to
	represent the integer i in binary*)
let bits_from_int i = to_int(floor ((log2 (of_int i)) /. 4.0 +. 1.0)) * 4

(**/**)

let smt_id = function
	| Variable(s)	-> s
	| _				-> "???" (* Not the case by construction of parser *)

let rec smt_lit a = function
	| Not(lit)	-> sprintf "(not %s)" (smt_lit a lit)
	| v			-> sprintf "(%s %s)" (smt_id v) a

let rec smt_loc = function
	| Not(True)	-> "false"
	| Not(loc)	-> sprintf "(not %s)" (smt_loc loc)
	| True		-> "true"
	| v			-> "(" ^ smt_id v ^ " i)"

let rec smt_pre o v = function
	| Not(True)	-> "false"
	| Not(loc)	-> sprintf "(not %s)" (smt_pre o v loc)
	| True		-> "true"
	| s			-> sprintf "(%s (%s i (bvneg %s)))" (smt_id s) o v

let rec smt_init = function
	| Not(True)	-> "false"
	| Not(loc)	-> sprintf "(not %s)" (smt_init loc)
	| True		-> "true"
	| v			-> "(" ^ smt_id v ^ " 0)"

let rec inputs_int i acc =
	match i with
		| []		-> acc
		| h :: t	-> inputs_int t (acc ^ sprintf "(declare-fun %s (Int) Bool)\n" h)

let rec definitions_int d acc =
	match d with
		| []			-> acc
		| (s, e) :: t	-> 
		(match e with 
			| Equivalence(x, y)	-> definitions_int t (acc ^ sprintf "(define-fun %s ((i Int)) Bool (= (%s i) (%s i)))\n" s (smt_id x) (smt_id y))
			| Implication(x, y)	-> definitions_int t (acc ^ sprintf "(define-fun %s ((i Int)) Bool (=> %s %s))\n" s (smt_lit "i" x) (smt_lit "i" y))
			| Memory(x, y)		-> definitions_int t (acc ^ sprintf "(define-fun %s ((i Int)) Bool (ite (= i 0) %s %s))\n" s (smt_loc x) (smt_pre "-" "1" y))
			| Next(x)			-> definitions_int t (acc ^ sprintf "(define-fun %s ((i Int)) Bool (%s (+ i 1)))\n" s (smt_id x))
			| _ -> "???")

let rec constraints_int c s acc =
	match c with
		| []		-> acc
		| h :: t	->
		(match h with
			| Init(x)	-> constraints_int t s (acc ^ sprintf "(assert (= %s true))\n" (smt_init x))
			| x			-> constraints_int t s (acc ^ sprintf "(assert (forall ((i Int)) (=> (< i %d) (= %s true))))\n" s (smt_loc x)))

let proofs_int p s = sprintf "(assert (= %s false))\n" (smt_lit (sprintf "%d" s) p)

let rec inputs_bv i n acc =
	match i with
		| []		-> acc
		| h :: t	-> inputs_bv t n (acc ^ sprintf "(declare-fun %s ((_ BitVec %d)) Bool)\n" h n)

let rec definitions_bv d n acc =
	match d with
		| []			-> acc
		| (s, e) :: t	-> 
		(match e with 
		| Equivalence(x, y)	-> definitions_bv t n (acc ^ sprintf "(define-fun %s ((i (_ BitVec %d))) Bool (= (%s i) (%s i)))\n" s n (smt_id x) (smt_id y))
		| Implication(x, y)	-> definitions_bv t n (acc ^ sprintf "(define-fun %s ((i (_ BitVec %d))) Bool (=> %s %s))\n" s n (smt_lit "i" x) (smt_lit "i" y))
		| Memory(x, y)		-> definitions_bv t n (acc ^ sprintf "(define-fun %s ((i (_ BitVec %d))) Bool (ite (= i #x0) %s %s))\n" s n (smt_loc x) (smt_pre "bvadd" "#x1" y))
		| Next(x)			-> definitions_bv t n (acc ^ sprintf "(define-fun %s ((i (_ BitVec %d))) Bool (%s (bvadd i #x1)))\n" s n (smt_id x))
		| _ -> "???")

let rec constraints_bv c n s acc =
	match c with
		| []		-> acc
		| h :: t	->
		(match h with
			| Init(x)	-> constraints_bv t n s (acc ^ sprintf "(assert (= %s true))\n" (smt_init x))
			| x			-> constraints_bv t n s (acc ^ sprintf "(assert (forall ((i (_ BitVec %d))) (=> (bvult i #x%x) (= %s true))))\n" n s (smt_loc x)))

let proofs_bv p s = sprintf "(assert (= %s false))\n" (smt_lit (sprintf "#x%x" s) p)

(**/**)

(** [generate_smt_bv path l n a] is used to write SMT formulas
	in the	file [path] - of the BitVec type (bit fields) - from
	the AST [a] built	from an	LLL file. The aim is to perform BMC
	(Bounded Model Checking) and therefore to set as parameters the
	maximum number of timesteps to check [l] and the	lookahead
	[n]. The function uses [bits_from_int] to	generate formulas
	with the correct number of bits.
	@param path path
	@param l timesteps 
	@param n lookahead*)		
let generate_smt_bv path l n = function
	| Some a	->
	let b = bits_from_int l in
	for p = 1 to length a.proofs do
		if ((nth a.proofs (p - 1)) != True) then
		(if not (file_exists (sprintf "%s/po%d" path p) && is_directory (sprintf "%s/po%d" path p)) then mkdir (sprintf "%s/po%d" path p) 0o755;
		let solved = ref false in
		for i = 0 to l do
			let file = open_out (sprintf "%s/po%d/%d.smt" path p i) in
			let content =
				"(set-logic ALL)\n\n"
				^ (inputs_bv a.inputs b "") ^ "\n"
				^ (definitions_bv a.definitions b "") ^ "\n"
				^ (constraints_bv a.constraints b (l + n) "") ^ "\n"
				^ (proofs_bv (nth a.proofs (p - 1)) i) ^ "\n" 
				^ "(check-sat)\n(get-model)\n(exit)\n"
			in
			fprintf file "%s" content; close_out file;
			if not !solved then
			(let input = open_process_in (sprintf "z3 %s/po%d/%d.smt" path p i) in
			let res = input_line input in
			printf "[+] PO%d : z3 %s\t@%d\n" p res i;
			if res = "sat" then solved := true);
		done);
	done
	| None		-> printf "[+] -smt : AST Invalid\n"

(** [generate_smt_int path l n a] is used to write SMT formulas
	in the	file [path] - of the Int type - from the AST [a] built
	from an	LLL file. The aim is to perform BMC	(Bounded Model
	Checking) and therefore to set as parameters the maximum number
	of timesteps to check [l] and the	lookahead [n].*)	
let generate_smt_int path l n = function
	| Some a	->
	for p = 1 to length a.proofs do
		if ((nth a.proofs (p - 1)) != True) then
		(if not (file_exists (sprintf "%s/po%d" path p) && is_directory (sprintf "%s/po%d" path p)) then mkdir (sprintf "%s/po%d" path p) 0o755;
		let solved = ref false in
		for i = 0 to l do
			let file = open_out (sprintf "%s/po%d/%d.smt" path p i) in
			let content =
				"(set-logic ALL)\n\n"
				^ (inputs_int a.inputs "") ^ "\n"
				^ (definitions_int a.definitions "") ^ "\n"
				^ (constraints_int a.constraints (l + n) "") ^ "\n"
				^ (proofs_int (nth a.proofs (p - 1)) i) ^ "\n" 
				^ "(check-sat)\n(get-model)\n(exit)\n"
			in
			fprintf file "%s" content; close_out file;
			if not !solved then
			(let input = open_process_in (sprintf "z3 %s/po%d/%d.smt" path p i) in
			let res = input_line input in
			printf "[+] PO%d : z3 %s\t@%d\n" p res i;
			if res = "sat" then solved := true);
		done);
	done
	| None		-> printf "[+] -smt : AST Invalid\n"